SUPPORTED_FUNCTIONS = [
# software specific
	'getDriverDate',
	'getImageArch',
	'getMachineKernelFile',
	'getMachineMKUBIFS',
	'getMachineMtdKernel',
	'getMachineMtdRoot',
	'getMachineRootFile',
	'getMachineUBINIZE',
	'getImageFileSystem',
# Distro/Build
	'getFeedsUrl',
	'getImageDistro',
	'getOEVersion',
	'getImageVersion',
	'getImageBuild',
	'getImageDevBuild',
	'getImageType',
	'getImageFolder',
	getMachineBuild'',
# These should be the same in all distros, but with non-OE-Alliance distros all bets are off.
	'getMachineName',
	'getMachineProcModel',
	'getBoxType',
# Manufacturer
	'getMachineMake',
	'getMachineBrand',
# Hardware specific functions
	'getBrandOEM',
	'getDisplayType',
	'getHaveAVJACK',
	'getHaveCI',
	'getHaveDVI',
	'getHaveHDMI',
	'getHaveHDMIinFHD',
	'getHaveHDMIinHD',
	'getHaveMiniTV',
	'getHaveRCA',
	'getHaveSCART',
	'getHaveSCARTYUV',
	'getHaveTranscoding1',
	'getHaveWOL',
	'getHaveWWOL',
	'getHaveYUV',
	'getHaveTranscoding2',]

IMPORTED_FUNCTIONS = [
# software specific
#	'getDriverDate',
	'getImageArch',
	'getMachineKernelFile',
	'getMachineMKUBIFS',
	'getMachineMtdKernel',
	'getMachineMtdRoot',
	'getMachineRootFile',
	'getMachineUBINIZE',
	'getImageFileSystem',
# Distro/Build
#	'getFeedsUrl',
#	'getImageDistro',
#	'getOEVersion',
#	'getImageVersion',
#	'getImageBuild',
#	'getImageDevBuild',
#	'getImageType',
	'getImageFolder',
	getMachineBuild'',
# These should be the same in all distros, but with non-OE-Alliance distros all bets are off.
	'getMachineName',
	'getMachineProcModel',
	'getBoxType',
# Manufacturer
	'getMachineMake',
	'getMachineBrand',
# Hardware specific functions
	'getBrandOEM',
	'getDisplayType',
	'getHaveAVJACK',
	'getHaveCI',
	'getHaveDVI',
	'getHaveHDMI',
	'getHaveHDMIinFHD',
	'getHaveHDMIinHD',
	'getHaveMiniTV',
	'getHaveRCA',
	'getHaveSCART',
	'getHaveSCARTYUV',
	'getHaveTranscoding1',
	'getHaveWOL',
	'getHaveWWOL',
	'getHaveYUV',
#	'getHaveTranscoding2',
	]
